"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ["app.py"]
DATA_FILES = []
OPTIONS = {
    'includes': [
        "GUI.py",
        "countDown.py",
        "ExcelFunctions.py",
        "pairing.py",
        "window.py",
    ],
    'resources': ["./databases/*", "./classes/*", "./excel/*"],
    "iconfile": "app.icns"
}

setup(
    app=APP,
    data_files=DATA_FILES,
    install_requires=[
        'PySide6',
    ],
    options={'py2app':OPTIONS},
    setup_requires=["py2app"],
)

